-- Q1.What is the total revenue generated by the business?
SELECT
    SUM(payment_value) AS Total_Revenue
FROM olist_order_payments_dataset;
--- Business Insight:
-- The business generated total revenue of R$16,008,872.12.

-- Q2.What is the average order value?
SELECT
    AVG(payment_value) AS Average_Order_Value
FROM olist_order_payments_dataset;
--- Business Insight:
-- Customers spent an average of R$154.10 per payment.

-- Q3.How has the monthly revenue changed over time?
SELECT
    YEAR(order_purchase_timestamp) AS Year,
    MONTH(order_purchase_timestamp) AS Month,
    SUM(payment_value) AS Revenue
FROM olist_orders_dataset o
JOIN olist_order_payments_dataset p
ON o.order_id = p.order_id
GROUP BY
    YEAR(order_purchase_timestamp),
    MONTH(order_purchase_timestamp)
ORDER BY Year, Month;
/* Business Insight:
- Revenue showed a strong upward trend from 2017 to 2018.
- April 2018 recorded the highest monthly revenue (1.16M).
- Very low revenue in 2016 and late 2018 is due to partial data availability in the dataset.*/

-- Q4.Which payment methods are most preferred by customers?
SELECT
    payment_type,
    COUNT(*) AS Total_Transactions,
    SUM(payment_value) AS Total_Revenue
FROM olist_order_payments_dataset
GROUP BY payment_type
ORDER BY Total_Transactions DESC;
--- Business Insight:
-- Credit cards are the dominant payment method, accounting for 76,795 transactions and 78.34% of total revenue.
-- Boleto is the second most popular payment method.

-- Q5.What is the average payment value by payment method?
SELECT
    payment_type,
    AVG(payment_value) AS Average_Payment_Value
FROM olist_order_payments_dataset
GROUP BY payment_type
ORDER BY Average_Payment_Value DESC;
--- Business Insight:
-- Credit card payments have the highest average payment value (163.32).
-- Voucher payments have the lowest average payment value (65.70).

-- Q6.What percentage of total revenue does each payment method contribute?
SELECT
    payment_type,
    SUM(payment_value) AS Revenue,
    ROUND(
        SUM(payment_value) * 100.0 /
        (SELECT SUM(payment_value) FROM olist_order_payments_dataset),
        2
    ) AS Revenue_Percentage
FROM olist_order_payments_dataset
GROUP BY payment_type
ORDER BY Revenue DESC;
/* Business Insight:
- Credit cards contribute 78.34% of total revenue, making them the primary revenue source.
- Boleto contributes 17.92%, while other payment methods together contribute less than 4%.
-------------------------------------------------------------------------------------------------
Recommendation
Optimise revenue growth by promoting the most preferred payment methods, 
monitoring monthly revenue trends, and using targeted promotions during low-performing
periods to maximise sales and improve payment conversion.